title: Weather REST API
author: fd-col
  name: fd-col
  email: s1093242@studenti.univpm.it

description: 

# Build settings

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
