title: Progetto Weather APP
author: fd-col
  name: fd-col
  email: federicocolleluori@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  L’applicazione presente nella repository è una REST API in grado di fornire 
  un prototipo di informazioni meteorologiche precedentemente salvate in un dataset che contiene: 
  dati storici, attuali e previsioni future (tutte relative ad un periodo prestabilito).
# Build settings

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
